HOMESTAY_SH/HOMESTAY_SH/Controllers/HomestayController.cs
using HOMESTAY_SH.Database_ADO;
using HOMESTAY_SH.Models;
using SWEET_HOME.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static HOMESTAY_SH.Models.HomestayDetailViewModel;

namespace SWEET_HOME.Controllers
{
    public class HomestayController : Controller
    {
        // GET: Homestay
        public ActionResult Homestay_item_best()
        {
            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                // Lấy danh sách các homestay có điểm đánh giá >= 3.5 và join với bảng AnhHomestay
                var homestayBest = db.Homestays
                                      .Where(h => h.DiemTrungBinh >= 3.5)
                                      .OrderByDescending(h => h.DiemTrungBinh)
                                      .Select(h => new HomestayItemBestViewModel
                                      {
                                          MaHomestay = h.MaHomestay,
                                          TenHomestay = h.TenHomestay,
                                          MoTa = h.MoTa,
                                          TienNghi = h.TienNghi,
                                          DienTich = h.DienTich,
                                          DiemTrungBinh = h.DiemTrungBinh,
                                          AnhChinh = h.AnhHomestay.AnhChinh,

                                      })
                                      .ToList();

                return View("Homestay_Item_Best", homestayBest); // Return the full view with images
            }
        }

        public ActionResult Homestay_item_discount()
        {
            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                // Lấy danh sách các homestay có điểm đánh giá <= 3.5 và join với bảng AnhHomestay
                var homestayDiscount = (from homestay in db.Homestays
                                        join khuvuc in db.KhuVucs
                                        on homestay.MaKhuVuc equals khuvuc.MaKhuVuc // Join với MaKhuVuc thay vì TenKhuVuc
                                        join anh in db.AnhHomestays
                                        on homestay.MaAnh equals anh.MaAnh // Join với MaAnh
                                        where homestay.DiemTrungBinh <= 3.5
                                        orderby homestay.DiemTrungBinh descending
                                        select new HomestayItemDiscount
                                        {
                                            MaHomestay = homestay.MaHomestay,
                                            TenHomestay = homestay.TenHomestay,
                                            TenKhuVuc = khuvuc.TenKhuVuc,
                                            DiemTrungBinh = homestay.DiemTrungBinh,
                                            AnhChinh = anh.AnhChinh // Lấy hình ảnh chính từ bảng AnhHomestay
                                        }).ToList();




                return View("Homestay_Item_Discount", homestayDiscount); // Return the data to the view
            }
        }

        //search
        public ActionResult Search(string searchQuery)
        {
            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                var homestay = (from hs in db.Homestays
                                where hs.TenHomestay.Contains(searchQuery)
                                select new { hs.MaHomestay }).FirstOrDefault();

                if (homestay == null)
                {
                    // Nếu không tìm thấy homestay, có thể hiển thị thông báo hoặc quay về trang chủ
                    TempData["Message"] = "Không tìm thấy homestay nào phù hợp!";
                    return RedirectToAction("Index", "Home");
                }

                // Chuyển hướng sang trang chi tiết của homestay
                return RedirectToAction("Detail", new { MaHomestay = homestay.MaHomestay });
            }
        }
        public ActionResult SearchSuggestions(string keyword)
        {
            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                var suggestions = db.Homestays
                    .Where(hs => hs.TenHomestay.Contains(keyword))
                    .Select(hs => new
                    {
                        hs.MaHomestay,
                        hs.TenHomestay,
                        hs.DiaChi
                    })
                    .ToList();

                return Json(suggestions, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult Detail(string MaHomestay, string maKhachHang)
        {
           
            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                var Detailhomestay = (from hs in db.Homestays
                                      join kv in db.KhuVucs on hs.MaKhuVuc equals kv.MaKhuVuc
                                      join anh in db.AnhHomestays on hs.MaAnh equals anh.MaAnh
                                      where hs.MaHomestay == MaHomestay
                                      select new HomestayDetailViewModel
                                      {
                                          MaHomestay = hs.MaHomestay,
                                          TenHomestay = hs.TenHomestay,
                                          TenKhuVuc = kv.TenKhuVuc,
                                          DiaChi = hs.DiaChi,
                                          GiaThue = hs.GiaThue,
                                          AnhChinh = anh.AnhChinh,
                                          AnhPhu1 = anh.AnhPhu1,
                                          AnhPhu2 = anh.AnhPhu2,
                                          AnhPhu3 = anh.AnhPhu3,
                                          AnhPhu4 = anh.AnhPhu4,
                                          SoLuongKhach = hs.SoLuongKhach,
                                          DienTich = hs.DienTich,
                                          MoTa = hs.MoTa,
                                          TienNghi = hs.TienNghi
                                      }).FirstOrDefault();

                if (Detailhomestay == null) return HttpNotFound();
                return View(Detailhomestay);
            }
        }
        private string GenerateMaCTDatHomestay()
        {
            // Logic sinh mã đặt homestay duy nhất
            // Ví dụ: DH + mã tự tăng
            return "DH" + DateTime.Now.ToString("yyyyMMdd") + new Random().Next(1000, 9999).ToString();
        }

        private string GenerateMaThanhToan()
        {
            return "TT" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
        }
        [HttpGet]
        public ActionResult DatHomestay(string MaHomestay)
        {
            using (var db = new QLH_SWEETHOMEEntities())
            {
                var maKhachHang = Session["MaKhachHang"] as string;
                if (string.IsNullOrEmpty(maKhachHang))
                {
                    TempData["ErrorMessage"] = "Vui lòng đăng nhập để đặt homestay.";
                    return RedirectToAction("Login", "Account");
                }

                var currentUser = db.KhachHangs.Find(maKhachHang);
                if (currentUser == null)
                {
                    TempData["ErrorMessage"] = "Không tìm thấy thông tin người dùng.";
                    return RedirectToAction("Login", "Account");
                }

                var homestay = db.Homestays.Find(MaHomestay);
                if (homestay == null)
                {
                    ModelState.AddModelError("", "Homestay không tồn tại hoặc đã bị xóa.");
                    return RedirectToAction("Index", "Home");
                }

                // Ánh xạ dữ liệu từ DichVus vào DichVuViewModel
                var dichVus = db.DichVus.Select(dv => new DichVuViewModel
                {
                    MaDichVu = dv.MaDichVu,
                    TenDichVu = dv.TenDichVu,
                    GiaDichVu = dv.GiaDichVu ?? 0,  // Giá dịch vụ có thể là null, nên phải xử lý
                    MoTaDichVu = dv.MoTaDichVu
                }).ToList();

                var bookingViewModel = new HomestayBookingViewModel
                {
                    MaHomestay = MaHomestay,
                    TenHomestay = homestay.TenHomestay,
                    GiaThue = homestay.GiaThue,
                    MaKhachHang = maKhachHang,
                    TenKhachHang = currentUser.TenKhachHang,
                    Email = currentUser.Email,
                    SDT = currentUser.SDT,
                    NgayDat = DateTime.Now,
                    NgayNhan = DateTime.Now,
                    NgayTra = DateTime.Now.AddDays(1),
                    TrangThai = "Chờ xác nhận",
                    DichVuAvailable = dichVus,  // Gán danh sách dịch vụ đã ánh xạ vào ViewModel
                    SelectedDichVuIds = new List<string>()
                };

                return View(bookingViewModel);
            }
        }
        //public ActionResult DatHomestay(int maHomestay)
        //{
        //    var homestay = _homestayService.GetHomestayById(maHomestay); // Lấy thông tin homestay
        //    var dichVuAvailable = _dichVuService.GetDichVuByHomestay(maHomestay); // Lấy danh sách dịch vụ

        //    var model = new HomestayBookingViewModel
        //    {
        //        MaHomestay = homestay.MaHomestay,
        //        TenHomestay = homestay.TenHomestay,
        //        GiaThue = homestay.GiaThue,
        //        DichVuAvailable = dichVuAvailable // Truyền danh sách dịch vụ
        //    };

        //    return View(model);
        //}


        [HttpPost]
        public ActionResult DatHomestay(HomestayBookingViewModel model)
        {

HOMESTAY_SH/HOMESTAY_SH/Controllers/SortController.cs
using HOMESTAY_SH.Database_ADO;
using HOMESTAY_SH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace HOMESTAY_SH.Controllers
{
    public class SortController : Controller
    {

        public ActionResult AllHomestay(int? page)
        {
            int pageSize = 5; // Số lượng homestay trên mỗi trang
            int pageNumber = page ??1; // Trang hiện tại, mặc định là 1

            using (QLH_SWEETHOMEEntities db = new QLH_SWEETHOMEEntities())
            {
                // Lấy tổng số bản ghi
                var totalRecords = db.Homestays.Count();

                // Lấy danh sách homestay cho trang hiện tại
                var Allhomestay = (from homestay in db.Homestays
                                   join khuvuc in db.KhuVucs
                                   on homestay.MaKhuVuc equals khuvuc.MaKhuVuc
                                   join anh in db.AnhHomestays
                                   on homestay.MaAnh equals anh.MaAnh
                                   orderby homestay.TenHomestay // Sắp xếp theo tên
                                   select new HomestayDetailViewModel
                                   {
                                       MaHomestay = homestay.MaHomestay,
                                       TenHomestay = homestay.TenHomestay,
                                       TenKhuVuc = khuvuc.TenKhuVuc,
                                       DiemTrungBinh = homestay.DiemTrungBinh,
                                       TienNghi = homestay.TienNghi,
                                       AnhChinh = anh.AnhChinh
                                   })
                                  .Skip((pageNumber - 1) * pageSize)
                                  .Take(pageSize)
                                  .ToList();

                // Tạo dữ liệu phân trang để gửi đến View
                ViewBag.TotalPages = (int)Math.Ceiling((double)totalRecords / pageSize);
                ViewBag.CurrentPage = pageNumber;

                return View("AllHomestay", Allhomestay);
            }
        }


    }
}

HOMESTAY_SH/HOMESTAY_SH/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/CSS/globals.css" />
    <link rel="stylesheet" href="~/CSS/Main-css.css" />
    <script src="~/Script/script.js" defer></script>
    <script src="https://kit.fontawesome.com/11158556be.js" crossorigin="anonymous"></script>
</head>
<title>@ViewBag.Title</title>
<body>
    <div class="main-page">
        <div class="div">
            <div class="overlap">
                <div class="rectangle"></div>
                <div class="search-bar">
                    <div class="overlap-group">
                        <img class="image" src="https://c.animaapp.com/crHRk4Ww/img/image-2@2x.png" />
                        <form method="get" action="@Url.Action("Search", "Homestay")">
                            <input type="text" placeholder="Searching..." name="searchQuery" />
                            <button type="submit" class="img-button">
                                <img class="img" src="https://c.animaapp.com/crHRk4Ww/img/image-3@2x.png" />
                            </button>
                        </form>
                    </div>
                </div>

                <div class="group">
                    <div class="account-dropdown">
                        <img class="image-2" src="https://c.animaapp.com/crHRk4Ww/img/image-8@2x.png" />
                        <div class="text-wrapper-2">MY ACCOUNT</div>
                        <div class="dropdown-content">
                            <a href="@Url.Action("Login", "Account")">Login</a>
                            <a href="@Url.Action("Register", "Account")">Register</a>
                        </div>
                    </div>
                    <a href="@Url.Action("Logout", "Account")">
                        <img class="imagelog" src="~/img/logout.png" />
                    </a>

                </div>

                <img class="picture-header" src="https://c.animaapp.com/crHRk4Ww/img/pictureheader.png" />
                <div class="text-wrapper-3">SWEET HOME</div>
                <div class="text-wrapper-4">@Html.ActionLink("Homestay", "AllHomestay", "Sort", null, new { @class = "home-link" })</div></div>
                <div class="text-wrapper-5"> @Html.ActionLink("Home", "Index", "Home", null, new { @class = "home-link" })</div>
                <div class="text-wrapper-6">City</div>
                <div class="text-wrapper-7">Service</div>
            </div>
            <div class="overlap-2">
                <img class="image-3" src="https://c.animaapp.com/crHRk4Ww/img/image-5@2x.png" />
                <img class="image-4" src="https://c.animaapp.com/crHRk4Ww/img/image-6.png" />
                <img class="image-5" src="https://c.animaapp.com/crHRk4Ww/img/image-4.png" />
                <img class="vector" src="https://c.animaapp.com/crHRk4Ww/img/vector-1.svg" />
                <p class="element-DISCOUNT">
                    <span class="span">40% </span>
                    <span class="text-wrapper-8">DISCOUNT</span>
                    <span class="span">&nbsp;</span>
                </p>
                <div class="text-wrapper-9">for first time booking</div>
                <div class="ellipse"></div>
                <div class="ellipse-2"></div>
                <div class="ellipse-3"></div>
                <div class="ellipse-4"></div>
                <div class="ellipse-5"></div>
            </div>
            <div class="slider-destination">
                <div class="slider-content">
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Ha Noi</div>
                        </div>
                    </div>
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Ho Chi Minh</div>
                        </div>
                    </div>
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Da Lat</div>
                        </div>
                    </div>
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Nha Trang</div>
                        </div>
                    </div>
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Khanh Hoa</div>
                        </div>
                    </div>
                    <div class="overlap-group-wrapper-3">
                        <div class="overlap-group-5">
                            <div class="rectangle-5"></div>
                            <img class="image-13" src="https://c.animaapp.com/crHRk4Ww/img/image-7@2x.png" />
                            <img class="vector-3" src="https://c.animaapp.com/crHRk4Ww/img/vector-6-1.svg" />
                            <div class="text-wrapper-34">Vung Tau</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="image-wrapper">
                <img class="image-9" src="https://c.animaapp.com/crHRk4Ww/img/image-11-6@2x.png" />
            </div>
            <div class="img-wrapper">
                <img class="image-10" src="https://c.animaapp.com/crHRk4Ww/img/image-11-7@2x.png" />
            </div>
            <div class="banner-adventurous">
                <div class="overlap-3">
                    <img class="image-6" src="https://c.animaapp.com/crHRk4Ww/img/image-18.png" />
                    <img class="vector-2" src="https://c.animaapp.com/crHRk4Ww/img/vector-6.svg" />
                    <div class="text-wrapper-10">FOR YOUR ADVENTUROUS JOURNEY</div>
                </div>
            </div>
            <div>


                @Html.Action("Homestay_item_best", "Homestay")
                



                @Html.Action("Homestay_item_Discount", "Homestay")
               

                @RenderBody()

                <div class="image-wrapper">
                    <img class="image-9" src="https://c.animaapp.com/crHRk4Ww/img/image-11-6@2x.png" />
                </div>
                <div class="img-wrapper">
                    <img class="image-10" src="https://c.animaapp.com/crHRk4Ww/img/image-11-7@2x.png" />
                </div>
                <div class="where-to-start-your">
                    <div class="rectangle-10"></div>
                    <p class="text-wrapper-39">WHERE TO START YOUR JOURNEY</p>
                </div>
                <div class="discount-this-week">
                    <div class="rectangle-10"></div>
                    <div class="text-wrapper-39">DISCOUNT THIS WEEK</div>
                </div>
                <div class="best-choices-from">
                    <div class="rectangle-10"></div>
                    <p class="text-wrapper-39">BEST CHOICES FROM THE VISITORS</p>
                </div>
            </div>
            <div class="footer-of-page">
                <div class="overlap-4">
                    <div class="group-2">
                        <div class="text-wrapper-11">Home</div>
                        <div class="text-wrapper-12">About us</div>
                        <div class="text-wrapper-13">Service</div>
                        <div class="text-wrapper-14">Rent</div>
                        <div class="text-wrapper-15">Contact</div>
                        <div class="text-wrapper-16">CONTENT</div>
                    </div>
                    <div class="group-3">
                        <div class="text-wrapper-17">Price</div>
                        <p class="booking">
                            <span class="text-wrapper-18">Booking</span> <span class="text-wrapper-19">&nbsp;</span>
                        </p>
                        <div class="text-wrapper-13">Check out</div>
                        <div class="text-wrapper-16">DETAIL</div>
                    </div>
                    <div class="text-wrapper-20">SOCIAL MEDIA</div>
                    <div class="group-4">
                        <div class="text-wrapper-21">Meal</div>
                        <div class="text-wrapper-12">Cleaning</div>
                        <div class="text-wrapper-13">Host</div>
                        <div class="text-wrapper-16">SERVICE</div>
                    </div>
                    <div class="rectangle-2"></div>
                    <p class="p">SWEET HOME Coppyright 2024 - 2099 Our Company T.V All rights reserved</p>
                </div>
            </div>
    </div>
        </div>>
    </body>
</html>

HOMESTAY_SH/HOMESTAY_SH/Views/Shared/_LayoutPage2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/CSS/globals.css" />
    <link rel="stylesheet" href="~/CSS/dashboard.css" />
    <script src="https://kit.fontawesome.com/11158556be.js" crossorigin="anonymous"></script>
    <title>@ViewBag.Admin</title>
</head>
<body>
    <div style="width: auto; height: 50px; background-color: #063146"></div>
    <input type="checkbox" id="check">
    <label for="check">
        <i class="fas fa-bars" id="btn"></i>
        <i class="fas fa-times" id="cancel"></i>
    </label>
    <div class="sidebar">
        <header>Admin</header>
        <ul>
            <li><a href="/Admin_Page/Dashboard"><i class="fas fa-qrcode"></i>Dashboard</a></li>
            <li><a href="/Admin_Page/AccountList"><i class="fas fa-stream"></i>Account</a></li>
            <li><a href="/Admin_Page/Homestay"><i class="fas fa-link"></i>Homestay</a></li>
            <li><a href="/Admin_Page/Employee"><i class="fas fa-stream"></i>Employee</a></li>
            <li><a href="/Admin_Page/Schedule"><i class="fas fa-calendar-week"></i>Schedule</a></li>
            <li><a href="/Admin_Page/Income"><i class="far fa-question-circle"></i>Income</a></li>
            <li><a href="/Admin_Page/Maintaince"><i class="fas fa-sliders-h"></i>Maintaince</a></li>

        </ul>
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>

HOMESTAY_SH/HOMESTAY_SH/Views/Shared/_LayoutPage3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/CSS/globals.css" />
    <link rel="stylesheet" href="~/CSS/Main-css.css" />
    <link rel="stylesheet" href="~/CSS/hiring-page-detail.css" />

    <script src="~/Script/script.js" defer></script>
    <script src="https://kit.fontawesome.com/11158556be.js" crossorigin="anonymous"></script>
</head>
<title>@ViewBag.Title</title>
<body>
    <div class="main-page">
        <div class="div">
            <div class="overlap">
                <div class="rectangle"></div>
                <div class="search-bar">
                    <div class="overlap-group">
                        <img class="image" src="https://c.animaapp.com/crHRk4Ww/img/image-2@2x.png" />
                        <form method="get" action="@Url.Action("Search", "Homestay")">
                            <input type="text" placeholder="Searching..." name="searchQuery" />
                            <button type="submit" class="img-button">
                                <img class="img" src="https://c.animaapp.com/crHRk4Ww/img/image-3@2x.png" />
                            </button>
                        </form>
                    </div>
                </div>
                <div class="group">
                    <div class="account-dropdown">
                        <img class="image-2" src="https://c.animaapp.com/crHRk4Ww/img/image-8@2x.png" />
                        <div class="text-wrapper-2">MY ACCOUNT</div>
                        <div class="dropdown-content">
                            <a href="@Url.Action("Login", "Account")">Login</a>
                            <a href="@Url.Action("Register", "Account")">Register</a>
                        </div>
                    </div>
                    <a href="@Url.Action("Logout", "Account")">
                        <img class="imagelog" src="~/img/logout.png" />
                    </a>

                </div>

                <img class="picture-header" src="https://c.animaapp.com/crHRk4Ww/img/pictureheader.png" />
                <div class="text-wrapper-3">SWEET HOME</div>
                <div class="text-wrapper-4">Homestay</div>
                <div class="text-wrapper-5"> @Html.ActionLink("Home", "Index", "Home", null, new { @class = "home-link" })</div>
                <div class="text-wrapper-6">City</div>
                <div class="text-wrapper-7">Service</div>
            </div>
            <div class="white-page">


                @RenderBody()

            </div>
            <div class="footer-of-page">
                <div class="overlap-4">
                    <div class="group-2">
                        <div class="text-wrapper-11">Home</div>
                        <div class="text-wrapper-12">About us</div>
                        <div class="text-wrapper-13">Service</div>
                        <div class="text-wrapper-14">Rent</div>
                        <div class="text-wrapper-15">Contact</div>
                        <div class="text-wrapper-16">CONTENT</div>
                    </div>
                    <div class="group-3">
                        <div class="text-wrapper-17">Price</div>
                        <p class="booking">
                            <span class="text-wrapper-18">Booking</span> <span class="text-wrapper-19">&nbsp;</span>
                        </p>
                        <div class="text-wrapper-13">Check out</div>
                        <div class="text-wrapper-16">DETAIL</div>
                    </div>
                    <div class="text-wrapper-20">SOCIAL MEDIA</div>
                    <div class="group-4">
                        <div class="text-wrapper-21">Meal</div>
                        <div class="text-wrapper-12">Cleaning</div>
                        <div class="text-wrapper-13">Host</div>
                        <div class="text-wrapper-16">SERVICE</div>
                    </div>
                    <div class="rectangle-2"></div>
                    <p class="p">SWEET HOME Coppyright 2024 - 2099 Our Company T.V All rights reserved</p>
                </div>
            </div>
        </div>
    </div>>
</body>
</html>